### ISSUE TITLE
Encountered an error

### ISSUE THREAD

**Issue by MacKenia** [vsnthdev/google-cse-lobechat#1]
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [400 Bad Request] Invalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[6].parameters.properties[1].value': Cannot find field.\nInvalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[6].parameters.properties[3].value': Cannot find field.\nInvalid JSON payload received. Unknown name \"default\" at 'tools[0].function_declarations[6].parameters.properties[4].value': Cannot find field. [{\"@type\":\"type.googleapis.com/google.rpc.BadRequest\",\"fieldViolations\":[{\"field\":\"tools[0].function_declarations[6].parameters.properties[1].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"default\\\" at 'tools[0].function_declarations[6].parameters.properties[1].value': Cannot find field.\"},{\"field\":\"tools[0].function_declarations[6].parameters.properties[3].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"default\\\" at 'tools[0].function_declarations[6].parameters.properties[3].value': Cannot find field.\"},{\"field\":\"tools[0].function_declarations[6].parameters.properties[4].value\",\"description\":\"Invalid JSON payload received. Unknown name \\\"default\\\" at 'tools[0].function_declarations[6].parameters.properties[4].value': Cannot find field.\"}]}]"
  },
  "provider": "google"
}

**Comment by MacKenia** [comment]
The error message above not cause by google-cse, this is real error log:
```json
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest:streamGenerateContent?alt=sse: [400 Bad Request] * GenerateContentRequest.tools[0].function_declarations[0].parameters.required[0]: property is not defined\n"
  },
  "provider": "google"
}
```

**Comment by vsnthdev** [comment]
> error message above not cause by google-cse

@MacKenia is there any further issue with the extension or shall I close the issue then?

**Comment by MacKenia** [comment]
Yes, when I use gemini api the google-cse won't work.

**Comment by vsnthdev** [comment]
Cool, thanks for using the google-cse extension 😀
